name: ci - react

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkou repo
        uses: actions/checkout@v4

        
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: xx
          
      - name: dependencies
        run: npm install

      - name: build
        run: npm run build
